[build]
  base = "client"                       # Base directory for the React app
  publish = "client/dist"                # Directory containing the built files
  command = "npm install && npm run build" # Command to build the app

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

