[build]
  base = "."                            # Root directory for the project
  publish = "client/dist"               # Directory where built files are located
  command = "npm run build-client"      # Command to build the client app

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
