[build]
  base = "paint-inventory-client/client"  # The subdirectory for the client app
  publish = "dist"                         # Directory containing the built files, relative to base
  command = "npm install && npm run build" # Install dependencies and build the client app

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
